// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gnlxvkajzfrfvehdljdy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdubHh2a2FqemZyZnZlaGRsamR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwNTY3ODEsImV4cCI6MjA1OTYzMjc4MX0.XjKJ3EkaQ10hJyq5pNcdT53j4MzrpCm_QXi4UMJj_Rk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);